# Configuration file for Pipeline B: Monocular Depth Estimation + Classification

# Data settings
data:
  root: "data/CW2-Dataset/data"
  image_size: 384  # Input image size for the model
  num_workers: 4
  batch_size: 32
  train_val_split: 0.8  # 80% training, 20% validation

# Model settings
model:
  name: "resnet18"  # Base CNN architecture
  pretrained: true  # Use pretrained weights
  num_classes: 2    # Binary classification: Table / No Table
  depth_model_type: "MiDaS_small"  # MiDaS depth estimation model type
  freeze_depth_estimator: false  # Whether to freeze the depth estimator during training

# Training settings
training:
  epochs: 100
  lr: 1e-3
  weight_decay: 1e-4
  lr_decay: 0.7
  lr_decay_step: 10
  early_stopping: 100  # Number of epochs with no improvement after which training will be stopped
  
  # Depth estimation loss weights
  depth_loss_weight: 1.0  # Set to 0.0 to disable depth loss when frozen
  si_weight: 1.0  # Scale-invariant MSE loss weight
  edge_weight: 0.1  # Edge-aware gradient loss weight

# Logging settings
logging:
  log_dir: "results/pipelineB"
  experiment_name: "depth_classification"
  use_tensorboard: true
  log_interval: 10  # Log every 10 batches
  save_checkpoint: true
  checkpoint_dir: "weights/pipelineB"

# Visualization settings
visualization:
  num_samples: 20  # Number of samples to visualize in evaluation 